### ISSUE TITLE
uppercasing framework name

### ISSUE THREAD

**Issue by elmarko** [what3words/w3w-swift-wrapper#3]
Hi, just started to work with this, and noticed that the framework name is lowercased i.e.

`import what3words`

standard naming conventions for Swift are to uppercase first letter of words for frameworks i.e. 

`import What3Words`

In saying this, I realise this would be a pretty big breaking change. So maybe something for a major update.

**Comment by dave-w3w** [comment]
It is now changed to W3WSwiftApi in version 3.6.0
This is a breaking change, but only affects the import statements.
Even still, we didn't opt to go to version 4.0 because we wanted to maintain version number solidarity with the actual API version number.
This release includes new completely different code, but the old version is left in for compatibility because we didn't go to 4.0.  It will probably be removed if and when v4 is released.
The only change people must make is to change their import statements. Every thing else should work.
Thanks!
